// GENERATED FILE — do not hand-edit. Regenerated by
// tools/generate-module-routes.cjs (the generate-module-routes Nx
// target, which build, typecheck and test depend on) from every
// apps/web/src/app/*/page.tsx file on disk. A module's screen layer
// only ever creates its own page.tsx inside its own directory —
// never edits this file or the root page.

export interface ModuleRoute {
  href: string;
  label: string;
}

export const moduleRoutes: ModuleRoute[] = [];
