import { Module } from '@nestjs/common';
import { LoggerModule } from 'nestjs-pino';
import { HealthController } from './health.controller';
// Generated by tools/generate-feature-modules.cjs (see that file's header)
// from every apps/api/src/app/*/*.module.ts on disk — never hand-edited,
// so no domain module's controller task ever edits this file or
// app.module.ts itself to register.
import { featureModules } from './feature-modules';

@Module({
  imports: [LoggerModule.forRoot(), ...featureModules],
  controllers: [HealthController],
  providers: [],
})
export class AppModule {}
