// GENERATED FILE — do not hand-edit. Regenerated by
// tools/generate-feature-modules.cjs (the generate-feature-modules Nx
// target, which test and build depend on) from every
// apps/api/src/app/*/*.module.ts file on disk. A module directory's
// controller layer only ever creates its own *.module.ts inside its own
// directory — never edits this file.

export const featureModules = [];
